name: CI

on:
  push:
    branches:
      - main
      - devel
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]  # Install package with test dependencies
          pip install pytest pytest-cov  # Install coverage-related packages

      - name: Run unittests
        run: python -m unittest discover tests

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
